Develop
hamsoter/food-management pull request #10
Opened 2022-07-28 16:18 UTC by ShineTiger

[의사코드](https://medium.com/djangogirlsseoul-codecamp/%EC%9D%98%EC%82%AC%EC%BD%94%EB%93%9C-pseudo-code-%EB%9E%80-d892a3479b1d) 를 제 식대로 적었습니다...
이전에는 쓴 코드는 너무 삽질+다시 쓸 수 없는 코드라고 판단해서 제 개인 브런치에만 두었습니다

지금은 간단하게 더미데이터를 쓰고있지만 
실제로는 백엔드에서 만들어주신 데이터를 쓰기 때문에 완전히 연관성이 없다고 생각해서
Assignees 에 프론트,백 둘다 추가했습니다

2022-07-28 16:25 UTC, Revi-Universe approved these changes

2022-07-30 07:40 UTC, hamsoter requested changes

2022-07-30 07:40 UTC, hamsoter commented on client/src/pages/AddMeal.tsx
> +    { id: 1, name: '바밤바' },
임의로 작성하신 음식의 더미데이터인가요? 이부분은 @Revi-Universe 님께 어떤 데이터가 올지 요청을 드려보죠!!!!

2022-07-30 07:40 UTC, hamsoter commented on client/src/pages/AddMeal.tsx
> +  State) input value / type : string / event : onChange
작성하신 의사코드를 개인 브랜치가 아닌 develop 브랜치에 머지하고자 하신 게 맞는 거죠? 
혹시 다른 사람들이 보기 편하기 위해 작성한 주석이 맞다면 올려주시고, 개인 공부용이라면 저번에 작성하신 브랜치에 커밋하시는 것도 좋다고 생각해요 (하지만 저번에도 말했다시피 이 방법은 매우 번거롭겠져ㅠㅠ)
+
[jsdocs](https://velog.io/@yijaee/JSDoc%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%B4-JavaScript-%ED%8C%8C%EC%9D%BC-%EB%AC%B8%EC%84%9C%ED%99%94%ED%95%98%EA%B8%B0#jsdoc-%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EA%B8%B0) 라는 js 기반 주석 작성법이 있더라구요! 이 방법대로 작성하면 jsdocs에서 자동으로 html 문서화를 해준다고 하는데, 사실 저희 프로젝트에 메서드 문서화까진 필요없다는 생각이 들고... 😄 

링크를 보시면 function에 주석을 달때 params, return 값이라던가 상세하게 적어두거든요! 복잡한 로직의 선언부에 이런걸 적어두는 것도 좋다고 생각해서 일단 한번 공유드려요!

예시코드
```js
/** @function addition
 * @param {number} a 연산하고자 하는 0 이상의 정수
 * @param {number} b 연산하고자 하는 0 이상의 정수
 * @returns {number} a + b
 */

const addition = (a, b) => a + b;
```

2022-07-30 07:40 UTC, hamsoter commented on client/src/pages/AddMeal.tsx
> +  const [autoCompleteBox, setautoCompleteBox] = useState(dummyData);
autoComplateBox는 어떤 역할을 하나요? dummyData 배열을 넣어두셨는데 이름을 봐서는 자동완성 추천단어들...? 같기도 하고... 괜찮으시다면 설명을 부탁드릴게요!

2022-08-02 09:45 UTC, ShineTiger commented on client/src/pages/AddMeal.tsx
> +    { id: 1, name: '바밤바' },
디스코드로 주신 데이터 확인했습니다! 
그러나 key 가 string으로 되어있고, mongoDB의 메소드도 있어서 적용하지 못했습니다. 
이부분은 제가 다시 문의드릴 예정입니다!

2022-08-02 09:46 UTC, ShineTiger commented on client/src/pages/AddMeal.tsx
> +  State) input value / type : string / event : onChange
의사코드 삭제했습니다! 다른사람이 보기 편하기위 작성한게 맞지만... 
지금 이렇게 코멘트를 주신걸 보면 가독성이 떨어진다고 판단, 삭제했습니다! 
다음 의사코드를 적을땐 좀 더 자세하게 적겠습니다!

2022-08-02 09:50 UTC, ShineTiger commented on client/src/pages/AddMeal.tsx
> +  const [autoCompleteBox, setautoCompleteBox] = useState(dummyData);
https://github.com/ShineTiger/food-management/commit/466f24b988ff3995cd8d9191ec46df640485e3b5

autoCompleteBox는 isCompleteBox로 이름을 변경했습니다! 자동완성박스를 보여주는 상태에요. 
그리고 위의 커밋 기준으로 completeList가 자동완성박스 안에 들어가는 리스트데이터 입니다!

2022-08-02 09:53 UTC, merged